### PR TITLE
Feature/sls deploy

### PR DESCRIPTION
**Pull request by krezzsy**
Cloudfront - d31h207unn4y4r.cloudfront.net 
S3 - http://krezzsy-nodejs-mp-spa.s3-website-us-east-1.amazonaws.com/

### CODE REVIEW

**Comment by kurk28** [comment]
all great, but according our task we need to save urls to `README`
and try to deploy on `eu-west-1`

- [ ] save url to README

**Comment by krezzsy** [comment]
> all great, but according our task we need to save urls to `README`
> and try to deploy on `eu-west-1`
> 
> * [ ]  save url to README

Sorry, can’t find a requirement regarding eu-west-1. Can you pls attach the reference?

**Comment by kurk28** [comment]
> Sorry, can’t find a requirement regarding eu-west-1. Can you pls attach the reference?

Will be enough to save URL to README

> and try to deploy on eu-west-1

It should sound like: did you try... Because in video was emphatically said that we should set `eu-west-1` region while deploying manually.

**Comment by krezzsy** [comment]
> > Sorry, can’t find a requirement regarding eu-west-1. Can you pls attach the reference?
> 
> Will be enough to save URL to README
> 
> > and try to deploy on eu-west-1
> 
> It should sound like: did you try... Because in video was emphatically said that we should set `eu-west-1` region while deploying manually.

I see. May I do it later? Unfortunately, I’m on VAC till the 5 April, I assume that README thing is rather minor thing that is not related to the task, so can you please rate the task if you agree on that it can be addressed later?
Thanks in advance, let me know in case you have some concerns

**Comment by kurk28** [comment]
Have a good vacation!

**Pull request merged**
